### ISSUE TITLE
Problem with MariaDB

### ISSUE THREAD

**Issue by uruzFR** [zwindler/ansible-nextcloud#10]
Hi, I have a problem when installing, I don’t know why.
I’ll put a screenshot in attachment.

![Capture d’écran du 2022-10-25 23-54-12](https://user-images.githubusercontent.com/111280713/197889571-cd27a2a4-4c8f-465d-bbb4-90c2ae94e723.png)

**Comment by zwindler** [comment]
Thanks I.ll take a look

**Comment by uruzFR** [comment]
The problem is solved, it was my server the problem !
